use AGN3;

insert into DependenciaGrupo(Nombre_Dep,Nombre_Grupo,DescriOrga)
	values 	    ('Direccion General','','Organigrama 2011'),
    ('Oficina de Planeamiento Archivistico','','Organigrama 2011'),
    ('Oficina de Planeamiento Archivistico','Grupo de Asistencia Tecnica y Gestion de Proyectos','Organigrama 2011'),
    ('Oficina de Planeamiento Archivistico','Grupo de Sistemas','Organigrama 2011'),
    ('Unidad de Control Interno','','Organigrama 2011'),
    ('Secretaría General y de Asusntos Jurídicos','','Organigrama 2011'),
    ('Secretaría General y de Asusntos Jurídicos','Grupo de Asuntos Jurídicos y Contratación','Organigrama 2011'),
    ('Secretaría General y de Asusntos Jurídicos','Grupo de Correspondencia y Archivo','Organigrama 2011'),
    ('División de Clasificación y Descripción','','Organigrama 2011'),
    ('División de Clasificación y Descripción','Grupo de Normatividad y Desarrollo de la Política Archivística','Organigrama 2011'),
    ('División de Clasificación y Descripción','Grupo de Conservación y Restauracion','Organigrama 2011'),
    ('División de Servicios al Público','','Organigrama 2011'),
    ('División de Reprografía y Automatizacion','','Organigrama 2011'),
    ('División de Programas Especiales','','Organigrama 2011'),
    ('División de Programas Especiales','Grupo de Capacitación y Asesoría al SNA','Organigrama 2011'),
    ('División de Programas Especiales','Grupo de Inspección y Vigilancia de Archivos del SNA','Organigrama 2011'),
    ('División Administrativa y Financiera','','Organigrama 2011'),
    ('División Administrativa y Financiera','Grupo de Talento Humano','Organigrama 2011'),
    ('División Administrativa y Financiera','Grupo de Presupuesto y Tesoreria','Organigrama 2011'),
    ('División Administrativa y Financiera','Grupo de Contabilidad','Organigrama 2011'),
    ('División Administrativa y Financiera','Grupo de Apoyo para la Adquisición de Bienes y Servicios','Organigrama 2011'),
    ('División Administrativa y Financiera','Grupo de Servicios Generales','Organigrama 2011'),
    ('Direción General','','Organigrama 2014'),
    ('Oficina Asesora de Planeacion','','Organigrama 2014'),
    ('Oficina Asesora Jurídica','','Organigrama 2014'),
    ('Oficina Asesora Jurídica','Grupo de Gestión Contractual','Organigrama 2014'),
    ('Oficina de Control Interno','','Organigrama 2014'),
    ('Secretaria General','','Organigrama 2014'),
    ('Secretaria General','Grupo de Archivo y Gestión Documental','Organigrama 2014'),
    ('Secretaria General','Grupo de Gestión Humana','Organigrama 2014'),
    ('Secretaria General','Grupo de Recursos Fisicos','Organigrama 2014'),
    ('Secretaria General','Grupo de Compras y Adquisiciones','Organigrama 2014'),
    ('Secretaria General','Grupo de Gestión Financiera','Organigrama 2014'),
    ('Secretaria General','Grupo de Sistemas','Organigrama 2014'),
    ('Subdirección de Sistema Nacional de Archivos','','Organigrama 2014'),
    ('Subdirección de Sistema Nacional de Archivos','Grupo de Articulación y Desarrollo del SNA','Organigrama 2014'),
    ('Subdirección de Sistema Nacional de Archivos','Grupo de Inspección y Vigilancia','Organigrama 2014'),
    ('Subdirección de Sistema Nacional de Archivos','Grupo de Archivos Étnicos y Derechos Humanos','Organigrama 2014'),
    ('Subdirección de Tecnologías de la Información Archivística y Documento Electrónico','','Organigrama 2014'),
    ('Subdirección de Tecnologías de la Información Archivística y Documento Electrónico','Grupo de Documentos Electrónicos y Preservación Digital','Organigrama 2014'),
    ('Subdirección de Tecnologías de la Información Archivística y Documento Electrónico','Grupo de Innovación y Apropiación de Tecnologías de Informacion Archivística','Organigrama 2014'),
    ('Subdirección de Gestión del Patrimonio Documental','','Organigrama 2014'),
    ('Subdirección de Gestión del Patrimonio Documental','Grupo de Conservación y Restauración del Patrimonio Documental','Organigrama 2014'),
    ('Subdirección de Gestión del Patrimonio Documental','Grupo de Investigación y Fondos Documentales Históricos','Organigrama 2014'),
    ('Subdirección de Gestión del Patrimonio Documental','Grupo de Organización, Descripción y Reprografía','Organigrama 2014'),
    ('Subdirección de Gestión del Patrimonio Documental','Grupo de Evaluación Documental y Transferencias Secundarias','Organigrama 2014'),
    ('Subdirección de Asistencia Técnica y Proyectos Archivísticos','','Organigrama 2014'),
    ('Subdirección de Asistencia Técnica y Proyectos Archivísticos','Grupo de Gestión de Proyectos Archivísticos','Organigrama 2014'),
    ('Subdirección de Asistencia Técnica y Proyectos Archivísticos','Grupo de Asistencia Técnica Archivística','Organigrama 2014');
    
insert into Cargo (Nombre_Cargo, Codigo, Grado,Sueldo)
	values ('Director General', 0015, 21, 6599891),
			('Secretario General', 0037, 18, 5498247),
			('Jefe de Oficina',0137, 15, 4747856),
			('Jefe Oficina Asesora Planeacion', 1045, 08, 4629373), 
			('Jefe Oficina Asesora Jurídica', 1045, 08, 4629373), 
			('Asesor', 1020, 05, 3346293), 
			('Subdirector General de Entidad', 0040, 14, 4651092),
			('Profesional Especializado', 2028, 17, 3729631),
			('Profesional Especializado', 2028, 16, 3545878), 
			('Profesional Especializado', 2028, 15, 3288880),
			('Profesional Especializado', 2028, 14, 297435), 
			('Profesional Especializado', 2028, 13, 2779762),
			('Profesional Especializado', 2028, 12, 2565641),
			('Profesional Universitario', 2044, 11, 2418255), 
			('Profesional Universitario', 2044, 09, 2243986), 
			('Profesional Universitario', 2044, 08, 2151378),
			('Restaurador', 2094, 09, 2243986), 
			('Restaurador', 2094, 08, 2151378),
			('Tecnico', 3100, 18, 2251917),
			('Tecnico', 3100, 17, 2049217), 
			('Tecnico Administrativo', 3124, 15, 1694203),
			('Tecnico Operativo',3132, 14, 1621055),
			('Auxiliar Administrativo', 4044, 22, 1534352),
			('Auxiliar Administrativo', 4044, 16, 1253616),
			('Auxiliar Administrativo', 4044, 14, 1164067),
			('Auxiliar Administrativo', 4044, 11, 1027665),
			('Secretario Ejecutivo', 4210, 22, 1534352),
			('Secretario Ejecutivo', 4210, 18, 1311843),
			('Secretario Ejecutivo', 4210, 20, 1387491),
			('Conductor Mecánico', 4103, 20, 1387491),
			('Conductor Mecánico', 4103, 17, 1280090),
			('Conductor Mecánico', 4103, 19, 1345682),
			('Auxiliar de Servicios Generales', 4064, 13, 1139113),
			('Auxiliar de Servicios Generales', 4064, 11, 1027665);

insert into Cargo (Nombre_Cargo, Codigo, Grado,Sueldo)
	values ('Profesional Universitario', 3020, 10, 1027665);


insert into Vinculacion (Nombre_Vinculacion)
	values ('Carrera Administrativa'),
			('Provisional'),
			('Ordinario');

select * from Cargo;
select * from DependenciaGrupo;